/**
 * Created on Aug 24 2020
 *
 * Copyright (c) 2020 Matt Jants
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *    are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * - Neither the name of the company, software or the names of its contributors 
 *    may be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 *  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 *  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, 
 *  ARISING FROM, OUT OF OR IN CONNECTION WITH THE USE OF THIS SOFTWARE OR OTHER DEALINGS IN THE SOFTWARE, 
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

public inherited sharing class StringIterator implements Iterator<String>, Iterable<String> {

  private String delimiter;
  private String text;

  public StringIterator(String text) {
    this(text, '\n');
  }

  public StringIterator(String text, String delimiter) {
    this.delimiter = delimiter;
    this.text = text;
  }

  public Boolean hasNext() {
    return this.text.length() > 0;
  }

  public String next() {
    String row;
    // get the index of the next delimiter
    Integer endPos = this.text.indexOf(this.delimiter);
    if (endPos == -1) {
      // when not found finish the row
      row = this.text;
      this.text = '';
    } else {
      // otherwise set the row to the text up to the next delimiter
      row = this.text.substring(0, endPos);
      // get the text after the next delimiter
      this.text = this.text.substring(endPos + this.delimiter.length(), this.text.length());
    }
    return row;
  }

  public Iterator<String> iterator() {
    return this;
  }

}
